CREATE TABLE IF NOT EXISTS data_nexus_db.company_information (
  company_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '公司ID',
  company_code VARCHAR(50) NOT NULL COMMENT '公司代码',
  company_name VARCHAR(100) NOT NULL COMMENT '公司名称',
  company_abbreviation VARCHAR(50) COMMENT '公司简称',
  registered_location ENUM('中国大陆', '中国香港', '境外') COMMENT '注册地点',
  company_type VARCHAR(50) COMMENT '公司类型',
  unified_social_credit VARCHAR(50) COMMENT '统一社会信用代码',
  registered_address VARCHAR(200) COMMENT '注册地址',
  registered_phone VARCHAR(20) COMMENT '注册电话',
  company_email VARCHAR(100) COMMENT '公司邮箱',
  establishment_date DATETIME COMMENT '成立日期',
  registered_capital DECIMAL(18, 2) COMMENT '注册资本',
  legal_representative_name VARCHAR(100) COMMENT '法定代表人姓名',
  legal_representative_phone VARCHAR(20) COMMENT '法定代表人电话',
  legal_representative_id VARCHAR(50) COMMENT '法定代表人身份证号',
  industry VARCHAR(50) COMMENT '行业',
  business_scope VARCHAR(200) COMMENT '经营范围',
  verified_customer TINYINT(1) COMMENT '是否已验证客户',
  szse_member TINYINT(1) COMMENT '是否深交所会员',
  szse_member_code VARCHAR(50) COMMENT '深交所会员代码',
  szse_member_abbreviation VARCHAR(50) COMMENT '深交所会员简称',
  customer_status VARCHAR(50) COMMENT '客户状态',
  country VARCHAR(50) COMMENT '所在国家',
  province VARCHAR(50) COMMENT '所在省份',
  city VARCHAR(50) COMMENT '所在城市',
  business_license_number VARCHAR(50) COMMENT '营业执照号码',
  business_license_expiry DATETIME COMMENT '营业执照到期日',
  primary_contact_name VARCHAR(100) COMMENT '主要联系人姓名',
  primary_contact_position VARCHAR(50) COMMENT '主要联系人职位',
  primary_contact_phone VARCHAR(20) COMMENT '主要联系人电话',
  primary_contact_email VARCHAR(100) COMMENT '主要联系人邮箱',
  INDEX idx_company_id (company_id),
  INDEX idx_company_code (company_code),
  INDEX idx_company_name (company_name),
  INDEX idx_unified_social_credit (unified_social_credit)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公司信息表';

CREATE TABLE IF NOT EXISTS history_records (
  record_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '记录ID',
  company_code VARCHAR(50) NOT NULL COMMENT '公司代码',
  operation_type VARCHAR(20) COMMENT '操作类型',
  operation_time DATETIME COMMENT '操作时间',
  operator VARCHAR(50) COMMENT '操作人',
  modified_field VARCHAR(50) COMMENT '修改字段',
  old_value VARCHAR(5000) COMMENT '旧值',
  new_value VARCHAR(5000) COMMENT '新值',
  remark VARCHAR(255) COMMENT '备注',
  INDEX idx_operation_type (operation_type),
  INDEX idx_company_code (company_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史记录表';