/*
数据插入脚本，用于前端分页数据显示测试
*/

--用例1 插入一家位于中国大陆的公司，是会员
INSERT INTO data_nexus_db.company_information (company_code, company_name, company_abbreviation, registered_location, company_type, unified_social_credit, registered_address, registered_phone, company_email, establishment_date, registered_capital, legal_representative_name, legal_representative_phone, legal_representative_id, industry, business_scope, verified_customer, szse_member, szse_member_code, szse_member_abbreviation, customer_status, country, province, city, business_license_number, business_license_expiry, primary_contact_name, primary_contact_position, primary_contact_phone, primary_contact_email)
VALUES ('C001', 'ABC公司', 'ABC', 1, '有限公司', '1234567890', '北京市朝阳区', '010-12345678', 'info@abc.com', '2022-01-01', 1000000.00, '张三', '13812345678', 'A987654', '制造业', '机械制造', true, true, 'SZ001', 'SZ', '正常', '中国', '北京市', '北京市', '123456789', '2025-01-01', '李四', '经理', '13887654321', 'li.si@abc.com');

--用例2 插入一家位于中国香港的公司，不是会员：
INSERT INTO data_nexus_db.company_information (company_code, company_name, company_abbreviation, registered_location, company_type, unified_social_credit, registered_address, registered_phone, company_email, establishment_date, registered_capital, legal_representative_name, legal_representative_phone, legal_representative_id, industry, business_scope, verified_customer, szse_member, customer_status, country, province, city, business_license_number, business_license_expiry, primary_contact_name, primary_contact_position, primary_contact_phone, primary_contact_email)
VALUES ('C002', 'XYZ有限公司', 'XYZ', 2, '有限公司', '9876543210', '香港中环', '+852-12345678', 'info@xyz.com', '2022-03-15', 500000.00, '李明', '+852-98765432', 'B987654', '服务业', '餐饮服务', true, false, '正常', '中国', '香港', '香港', '876543210', '2025-03-31', '王小红', '经理', '+852-67891234', 'wang.xiaohong@xyz.com');

--用例3 插入一家境外公司，不是会员
INSERT INTO data_nexus_db.company_information (company_code, company_name, company_abbreviation, registered_location, company_type, unified_social_credit, registered_address, registered_phone, company_email, establishment_date, registered_capital, legal_representative_name, legal_representative_phone, legal_representative_id, industry, business_scope, verified_customer, szse_member, customer_status, country, province, city, business_license_number, business_license_expiry, primary_contact_name, primary_contact_position, primary_contact_phone, primary_contact_email)
VALUES ('C003', 'DEF Company', 'DEF', 3, 'Limited', '987654321', '123 Main Street, New York', '+1-123-456-7890', 'info@defcompany.com', '2022-05-20', 2000000.00, 'John Doe', '+1-987-654-3210', 'C012345', 'Technology', 'Software Development', false, false, 'Active', 'United States', 'New York', 'New York', '654321', '2025-05-31', 'Jane Smith', 'Manager', '+1-234-567-8901', 'jane.smith@defcompany.com');

--用例4 插入一家位于境外的公司
INSERT INTO data_nexus_db.company_information (company_code, company_name, registered_location, company_type, unified_social_credit, registered_address, registered_phone, company_email, establishment_date, registered_capital, legal_representative_name, legal_representative_phone, legal_representative_id, industry, business_scope, verified_customer, szse_member, customer_status, country, province, city, business_license_number, business_license_expiry, primary_contact_name, primary_contact_position, primary_contact_phone, primary_contact_email)
VALUES ('C004', 'XYZ GmbH', '2', 'GmbH', '9876543210', 'Berlin', '+49-123456789', 'info@xyzgmbh.com', '2022-05-20', 800000.00, 'Max Mustermann', '+49-987654321', 'D987654', '制造业', '汽车零部件生产', true, false, '正常', '德国', '柏林', '柏林市', '876543210', '2026-05-31', 'Anna Schmidt', '经理', '+49-678912345', 'anna.schmidt@xyzgmbh.com');

--用例4 插入一家位于中国大陆的公司
INSERT INTO data_nexus_db.company_information (company_code, company_name, company_abbreviation, registered_location, company_type, unified_social_credit, registered_address, registered_phone, company_email, establishment_date, registered_capital, legal_representative_name, legal_representative_phone, legal_representative_id, industry, business_scope, verified_customer, szse_member, szse_member_code, szse_member_abbreviation, customer_status, country, province, city, business_license_number, business_license_expiry, primary_contact_name, primary_contact_position, primary_contact_phone, primary_contact_email)
VALUES ('C004', 'EFG有限公司', 'EFG', 1, '有限公司', '1234567890', '上海市浦东新区', '021-98765432', 'info@efg.com', '2022-07-01', 800000.00, '王五', '13987654321', 'D987654', '金融业', '投资管理', true, true, 'SZ002', 'SZ', '正常', '中国', '上海市', '上海市', '987654321', '2025-07-31', '赵六', '经理', '13912345678', 'zhao.liu@efg.com');

--用例5 插入一家位于日本的公司
INSERT INTO data_nexus_db.company_information (company_code, company_name, company_abbreviation, registered_location, company_type, unified_social_credit, registered_address, registered_phone, company_email, establishment_date, registered_capital, legal_representative_name, legal_representative_phone, legal_representative_id, industry, business_scope, verified_customer, szse_member, customer_status, country, province, city, business_license_number, business_license_expiry, primary_contact_name, primary_contact_position, primary_contact_phone, primary_contact_email)
VALUES ('C006', 'KLM株式会社', 'KLM', 3, '株式会社', '7654321098', '东京都中央区', '+81-123-456789', 'info@klm.co.jp', '2022-11-01', 9000000.00, '山田一郎', '+81-987-654321', 'F012345', '制造业', '汽车制造', false, false, 'Active', '日本', '东京都', '东京', '0987654321', '2025-11-30', '佐藤花子', '经理', '+81-234-567890', 'sato.hanako@klm.co.jp');

--用例6 插入一家位于境外的公司
INSERT INTO data_nexus_db.company_information (company_code, company_name, company_abbreviation, registered_location, company_type, unified_social_credit, registered_address, registered_phone, company_email, establishment_date, registered_capital, legal_representative_name, legal_representative_phone, legal_representative_id, industry, business_scope, verified_customer, szse_member, customer_status, country, province, city, business_license_number, business_license_expiry, primary_contact_name, primary_contact_position, primary_contact_phone, primary_contact_email)
VALUES ('C003', 'GHI有限公司', 'GHI', 3, '有限公司', '87654321', '境外地址', '+123-456789', 'info@ghi.com', '2022-03-01', 3000000.00, '赵四', '+123-456789', 'C987654', '服务业', '咨询服务', false, false, '正常', '境外', '境外省份', '境外城市', '654321098', '2025-03-01', '钱七', '经理', '+123-456789', 'qian.qi@ghi.com');
