import requests

def send_post_request(url, headers, data):
    try:
        response = requests.post(url, headers=headers, json=data)
        if response.status_code == 200 or response.status_code == 201:
            print("Request successful")
            print("Response:")
            print(response.text)
        else:
            print("Request failed with status code:", response.status_code)
    except requests.exceptions.RequestException as e:
        print("An error occurred:", e)

# 示例URL
url = "http://localhost:8080/companies/create"

# 请求头
headers = {
    "Content-Type": "application/json; charset=utf-8"
}

# 请求体数据
forms = [{
        "companyCode": "C001",
        "companyName": "ABC公司",
        "companyAbbreviation": "ABC",
        "companyType": "有限公司",
        "registeredLocation": "0",
        "unifiedSocialCredit": "123456789012345678",
        "registeredAddress": "北京市朝阳区",
        "registeredPhone": "010-12345678",
        "companyEmail": "info@abc.com",
        "establishmentDate": "2022-01-01",
        "registeredCapital": 1000000.00,
        "legalRepresentativeName": "张三",
        "legalRepresentativePhone": "13812345678",
        "legalRepresentativeId": "A987654",
        "industry": "制造业",
        "businessScope": "机械制造",
        "verifiedCustomer": True,
        "szseMember": True,
        "szseMemberCode": "SZ001",
        "szseMemberAbbreviation": "SZ",
        "customerStatus": "正常",
        "country": "中国",
        "province": "北京市",
        "city": "北京市",
        "businessLicenseNumber": "123456789",
        "businessLicenseExpiry": "2025-01-01",
        "primaryContactName": "李四",
        "primaryContactPosition": "经理",
        "primaryContactPhone": "13887654321",
        "primaryContactEmail": "li.si@abc.com",
    },
 {
        "companyCode": "C002",
        "companyName": "XYZ有限公司",
        "companyAbbreviation": "XYZ",
        "companyType": "有限公司",
        "registeredLocation": "1",
        "unifiedSocialCredit": "987654321098765432",
        "registeredAddress": "香港中环",
        "registeredPhone": "0085212345678",
        "companyEmail": "info@xyz.com",
        "establishmentDate": "2022-03-15",
        "registeredCapital": 500000.00,
        "legalRepresentativeName": "李明",
        "legalRepresentativePhone": "85298765432",
        "legalRepresentativeId": "B987654",
        "industry": "服务业",
        "businessScope": "餐饮服务",
        "verifiedCustomer": True,
        "szseMember": False,
        "szseMemberCode": "",
        "szseMemberAbbreviation": "",
        "customerStatus": "正常",
        "country": "中国",
        "province": "香港",
        "city": "香港",
        "businessLicenseNumber": "876543210",
        "businessLicenseExpiry": "2025-03-31",
        "primaryContactName": "王小红",
        "primaryContactPosition": "经理",
        "primaryContactPhone": "85267891234",
        "primaryContactEmail": "wang.xiaohong@xyz.com"
    },
    {
        "companyCode": "C003",
        "companyName": "DEF Company",
        "companyAbbreviation": "DEF",
        "companyType": "Limited",
        "registeredLocation": "2",
        "unifiedSocialCredit": "ABCDEFGHIJKLMNOPQ",
        "registeredAddress": "123 Main Street, New York",
        "registeredPhone": "11234567890",
        "companyEmail": "info@defcompany.com",
        "establishmentDate": "2022-03-15",
        "registeredCapital": 2000000.00,
        "legalRepresentativeName": "John Doe",
        "legalRepresentativePhone": "19876543210",
        "legalRepresentativeId": "C012345",
        "industry": "Technology",
        "businessScope": "Software Development",
        "verifiedCustomer": True,
        "szseMember": False,
        "szseMemberCode": "",
        "szseMemberAbbreviation": "",
        "customerStatus": "Active",
        "country": "United States",
        "province": "New York",
        "city": "New York",
        "businessLicenseNumber": "654321",
        "businessLicenseExpiry": "2025-05-31",
        "primaryContactName": "Jane Smith",
        "primaryContactPosition": "Manager",
        "primaryContactPhone": "85267891234",
        "primaryContactEmail": "jane.smith@defcompany.com"
    },
{
"companyCode": "C005",
"companyName": "EFG有限公司",
"companyAbbreviation": "EFG",
"companyType": "有限公司",
"registeredLocation": "0",
"unifiedSocialCredit": "9876543210ABCDE01",
"registeredAddress": "上海市浦东新区",
"registeredPhone": "021-98765432",
"companyEmail": "info@efg.com",
"establishmentDate": "2022-07-01",
"registeredCapital": 800000.00,
"legalRepresentativeName": "王五",
"legalRepresentativePhone": "13987654321",
"legalRepresentativeId": "D987654",
"industry": "金融业",
"businessScope": "投资管理",
"verifiedCustomer": True,
"szseMember": True,
"szseMemberCode": "SZ002",
"szseMemberAbbreviation": "SZ",
"customerStatus": "正常",
"country": "中国",
"province": "上海市",
"city": "上海市",
"businessLicenseNumber": "987654321",
"businessLicenseExpiry": "2025-07-31",
"primaryContactName": "赵六",
"primaryContactPosition": "经理",
"primaryContactPhone": "13912345678",
"primaryContactEmail": "zhao.liu@efg.com"
},
{
"companyCode": "C006",
"companyName": "KLM株式会社",
"companyAbbreviation": "KLM",
"companyType": "株式会社",
"registeredLocation": "2",
"unifiedSocialCredit": "1A2B3C4D5E6F7G8H9",
"registeredAddress": "东京都中央区",
"registeredPhone": "81123456789",
"companyEmail": "info@klm.co.jp",
"establishmentDate": "2022-11-01",
"registeredCapital": 9000000.00,
"legalRepresentativeName": "山田一郎",
"legalRepresentativePhone": "81987654321",
"legalRepresentativeId": "F012345",
"industry": "制造业",
"businessScope": "汽车制造",
"verifiedCustomer": False,
"szseMember": False,
"szseMemberCode": "",
"szseMemberAbbreviation": "",
"customerStatus": "Active",
"country": "日本",
"province": "东京都",
"city": "东京",
"businessLicenseNumber": "0987654321",
"businessLicenseExpiry": "2025-11-30",
"primaryContactName": "佐藤花子",
"primaryContactPosition": "经理",
"primaryContactPhone": "+81-234-567890",
"primaryContactEmail": "sato.hanako@klm.co.jp"
},
{
"companyCode": "C007",
"companyName": "GHI有限公司",
"companyAbbreviation": "GHI",
"companyType": "有限公司",
"registeredLocation": "2",
"unifiedSocialCredit": "XYZ123ABC456DEF78",
"registeredAddress": "境外地址",
"registeredPhone": "+123-456789",
"companyEmail": "info@ghi.com",
"establishmentDate": "2022-03-01",
"registeredCapital": 3000000.00,
"legalRepresentativeName": "赵四",
"legalRepresentativePhone": "+123-456789",
"legalRepresentativeId": "C987654",
"industry": "服务业",
"businessScope": "咨询服务",
"verifiedCustomer": False,
"szseMember": False,
"szseMemberCode": "",
"szseMemberAbbreviation": "",
"customerStatus": "正常",
"country": "境外",
"province": "境外省份",
"city": "境外城市",
"businessLicenseNumber": "654321098",
"businessLicenseExpiry": "2025-03-01",
"primaryContactName": "钱七",
"primaryContactPosition": "经理",
"primaryContactPhone": "+123-456789",
"primaryContactEmail": "qian.qi@ghi.com"
},
{
"companyCode": "C008",
"companyName": "JKL有限公司",
"companyAbbreviation": "JKL",
"companyType": "有限公司",
"registeredLocation": "0",
"unifiedSocialCredit": "65432109876543210",
"registeredAddress": "北京市海淀区",
"registeredPhone": "010-98765432",
"companyEmail": "info@jkl.com",
"establishmentDate": "2022-04-01",
"registeredCapital": 4000000.00,
"legalRepresentativeName": "王八",
"legalRepresentativePhone": "010-98765432",
"legalRepresentativeId": "D987654",
"industry": "科技",
"businessScope": "软件开发",
"verifiedCustomer": True,
"szseMember": True,
"szseMemberCode": "SZ002",
"szseMemberAbbreviation": "SZ",
"customerStatus": "正常",
"country": "中国",
"province": "北京市",
"city": "北京",
"businessLicenseNumber": "789654321",
"businessLicenseExpiry": "2025-04-01",
"primaryContactName": "孙九",
"primaryContactPosition": "经理",
"primaryContactPhone": "010-12345678",
"primaryContactEmail": "sun.jiu@jkl.com"
},
{
"companyCode": "C009",
"companyName": "MNO公司",
"companyAbbreviation": "MNO",
"companyType": "有限公司",
"registeredLocation": "1",
"unifiedSocialCredit": "00000000000000000",
"registeredAddress": "香港岛湾仔区",
"registeredPhone": "852-12345678",
"companyEmail": "info@mno.com",
"establishmentDate": "2022-05-01",
"registeredCapital": 5000000.00,
"legalRepresentativeName": "赵十",
"legalRepresentativePhone": "852-12345678",
"legalRepresentativeId": "E987654",
"industry": "零售",
"businessScope": "电子产品",
"verifiedCustomer": True,
"szseMember": False,
"szseMemberCode": "",
"szseMemberAbbreviation": "",
"customerStatus": "正常",
"country": "中国",
"province": "香港",
"city": "香港",
"businessLicenseNumber": "9876543210",
"businessLicenseExpiry": "2025-05-01",
"primaryContactName": "周十一",
"primaryContactPosition": "经理",
"primaryContactPhone": "852-98765432",
"primaryContactEmail": "zhou.shiyi@mno.com"
},
{
"companyCode": "C010",
"companyName": "XYZ Enterprises",
"companyAbbreviation": "XYZ",
"companyType": "Retail",
"registeredLocation": "2",
"unifiedSocialCredit": "11111111111111111",
"registeredAddress": "123 Main Street",
"registeredPhone": "987-654-3210",
"companyEmail": "info@abccorp.com",
"establishmentDate": "2010-01-15",
"registeredCapital": 1000000.00,
"legalRepresentativeName": "John Johnson",
"legalRepresentativePhone": "555-123-4567",
"legalRepresentativeId": "123456789",
"industry": "Consumer Goods",
"businessScope": "Wholesale distribution",
"verifiedCustomer": True,
"szseMember": False,
"szseMemberCode": "",
"szseMemberAbbreviation": "",
"customerStatus": "Active",
"country": "China",
"province": "Beijing",
"city": "Beijing",
"businessLicenseNumber": "BL123456",
"businessLicenseExpiry": "2023-09-30",
"primaryContactName": "Emily Smith",
"primaryContactPosition": "Sales Manager",
"primaryContactPhone": "555-987-6543",
"primaryContactEmail": "emily@abccorp.com"
},
{
"companyCode": "C011",
"companyName": "LMN有限公司",
"companyAbbreviation": "LMN",
"companyType": "制造业",
"registeredLocation": "0",
"unifiedSocialCredit": "22222222222222222",
"registeredAddress": "上海市浦东新区",
"registeredPhone": "021-98765432",
"companyEmail": "info@lmn.com",
"establishmentDate": "2015-10-01",
"registeredCapital": 3000000.00,
"legalRepresentativeName": "张三",
"legalRepresentativePhone": "021-98765432",
"legalRepresentativeId": "A987654",
"industry": "制造业",
"businessScope": "电子产品制造",
"verifiedCustomer": True,
"szseMember": False,
"szseMemberCode": "",
"szseMemberAbbreviation": "",
"customerStatus": "正常",
"country": "中国",
"province": "上海市",
"city": "上海",
"businessLicenseNumber": "987654321",
"businessLicenseExpiry": "2024-10-01",
"primaryContactName": "李四",
"primaryContactPosition": "经理",
"primaryContactPhone": "021-12345678",
"primaryContactEmail": "li.si@lmn.com"
},
{
"companyCode": "C012",
"companyName": "OPQ有限公司",
"companyAbbreviation": "OPQ",
"companyType": "服务业",
"registeredLocation": "0",
"unifiedSocialCredit": "33333333333333333",
"registeredAddress": "广州市天河区",
"registeredPhone": "020-12345678",
"companyEmail": "info@abc.com",
"establishmentDate": "2010-05-15",
"registeredCapital": 5000000.00,
"legalRepresentativeName": "李五",
"legalRepresentativePhone": "020-12345678",
"legalRepresentativeId": "B123456",
"industry": "广告",
"businessScope": "广告策划与设计",
"verifiedCustomer": True,
"szseMember": True,
"szseMemberCode": "SZ001",
"szseMemberAbbreviation": "SZ001",
"customerStatus": "正常",
"country": "中国",
"province": "广东省",
"city": "广州",
"businessLicenseNumber": "123456789",
"businessLicenseExpiry": "2023-12-31",
"primaryContactName": "王六",
"primaryContactPosition": "经理",
"primaryContactPhone": "020-98765432",
"primaryContactEmail": "wang.liu@abc.com"
},
{
"companyCode": "C013",
"companyName": "XYZ有限公司",
"companyAbbreviation": "XYZ",
"companyType": "贸易",
"registeredLocation": "0",
"unifiedSocialCredit": "44444444444444444",
"registeredAddress": "深圳市福田区",
"registeredPhone": "0755-12345678",
"companyEmail": "info@xyz.com",
"establishmentDate": "2018-09-20",
"registeredCapital": 2000000.00,
"legalRepresentativeName": "赵八",
"legalRepresentativePhone": "0755-12345678",
"legalRepresentativeId": "C123456",
"industry": "贸易",
"businessScope": "进出口业务",
"verifiedCustomer": True,
"szseMember": False,
"szseMemberCode": "",
"szseMemberAbbreviation": "",
"customerStatus": "正常",
"country": "中国",
"province": "广东省",
"city": "深圳",
"businessLicenseNumber": "9876543210",
"businessLicenseExpiry": "2024-09-20",
"primaryContactName": "钱九",
"primaryContactPosition": "经理",
"primaryContactPhone": "0755-98765432",
"primaryContactEmail": "qian.jiu@xyz.com"
},
{
"companyCode": "C014",
"companyName": "AAA有限公司",
"companyAbbreviation": "AAA",
"registeredLocation": "0",
"companyType": "金融",
"unifiedSocialCredit": "55555555555555555",
"registeredAddress": "北京市朝阳区",
"registeredPhone": "010-12345678",
"companyEmail": "info@efg.com",
"establishmentDate": "2019-07-10",
"registeredCapital": 8000000.00,
"legalRepresentativeName": "孙十",
"legalRepresentativePhone": "010-12345678",
"legalRepresentativeId": "D123456",
"industry": "金融",
"businessScope": "投资管理",
"verifiedCustomer": True,
"szseMember": True,
"szseMemberCode": "SZ003",
"szseMemberAbbreviation": "SZ003",
"customerStatus": "正常",
"country": "中国",
"province": "北京市",
"city": "北京",
"businessLicenseNumber": "3456789012",
"businessLicenseExpiry": "2023-07-10",
"primaryContactName": "周十一",
"primaryContactPosition": "经理",
"primaryContactPhone": "010-98765432",
"primaryContactEmail": "zhou.shiyi@efg.com"
}
]



# 发送POST请求
i = 0
for form in forms:
    send_post_request(url, headers=headers, data=form)
    