import requests

def send_post_request(url, headers, data):
    try:
        response = requests.post(url, headers=headers, json=data)
        if response.status_code == 200 or response.status_code == 201:
            print("Request successful")
            print("Response:")
            print(response.text)
        else:
            print("Request failed with status code:", response.status_code)
    except requests.exceptions.RequestException as e:
        print("An error occurred:", e)

# 示例URL
url = "http://localhost:8080/companies/create"

# 请求头
headers = {
    "Content-Type": "application/json; charset=utf-8"
}

# 请求体数据
forms = [{
    "company_code": "C001",
    "company_name": "ABC公司",
    "company_abbreviation": "ABC",
    "company_type": "有限公司",
    "registered_location": "0",
    "unified_social_credit": "123456789012345678",
    "registered_address": "北京市朝阳区",
    "registered_phone": "010-12345678",
    "company_email": "info@abc.com",
    "establishment_date": "2022-01-01",
    "registered_capital": 1000000.00,
    "legal_representative_name": "张三",
    "legal_representative_phone": "13812345678",
    "legal_representative_id": "A987654",
    "industry": "制造业",
    "business_scope": "机械制造",
    "verified_customer": True,
    "szse_member": True,
    "szse_member_code": "SZ001",
    "szse_member_abbreviation": "SZ",
    "customer_status": "正常",
    "country": "中国",
    "province": "北京市",
    "city": "北京市",
    "business_license_number": "123456789",
    "business_license_expiry": "2025-01-01",
    "primary_contact_name": "李四",
    "primary_contact_position": "经理",
    "primary_contact_phone": "13887654321",
    "primary_contact_email": "li.si@abc.com"
},
{
    "company_code": "C002",
    "company_name": "XYZ有限公司",
    "company_abbreviation": "XYZ",
    "company_type": "有限公司",
    "registered_location": "1",
    "unified_social_credit": "987654321098765432",
    "registered_address": "香港中环",
    "registered_phone": "0085212345678",
    "company_email": "info@xyz.com",
    "establishment_date": "2022-03-15",
    "registered_capital": 500000.00,
    "legal_representative_name": "李明",
    "legal_representative_phone": "85298765432",
    "legal_representative_id": "B987654",
    "industry": "服务业",
    "business_scope": "餐饮服务",
    "verified_customer": True,
    "szse_member": False,
    "szse_member_code": "",
    "szse_member_abbreviation": "",
    "customer_status": "正常",
    "country": "中国",
    "province": "香港",
    "city": "香港",
    "business_license_number": "876543210",
    "business_license_expiry": "2025-03-31",
    "primary_contact_name": "王小红",
    "primary_contact_position": "经理",
    "primary_contact_phone": "85267891234",
    "primary_contact_email": "wang.xiaohong@xyz.com"   
},
{
    "company_code": "C003",
    "company_name": "DEF Company",
    "company_abbreviation": "DEF",
    "company_type": "Limited",
    "registered_location": "2",
    "unified_social_credit": "ABCDEFGHIJKLMNOPQ",
    "registered_address": "123 Main Street, New York",
    "registered_phone": "11234567890",
    "company_email": "info@defcompany.com",
    "establishment_date": "2022-03-15",
    "registered_capital": 2000000.00,
    "legal_representative_name": "John Doe",
    "legal_representative_phone": "19876543210",
    "legal_representative_id": "C012345",
    "industry": "Technology",
    "business_scope": "Software Development",
    "verified_customer": True,
    "szse_member": False,
    "szse_member_code": "",
    "szse_member_abbreviation": "",
    "customer_status": "Active",
    "country": "United States",
    "province": "New York",
    "city": "New York",
    "business_license_number": "654321",
    "business_license_expiry": "2025-05-31",
    "primary_contact_name": "Jane Smith",
    "primary_contact_position": "Manager",
    "primary_contact_phone": "85267891234",
    "primary_contact_email": "jane.smith@defcompany.com"   
}, 
{
    "company_name": "XYZ GmbH",
    "company_code": "C004",
    "company_abbreviation": "",
    "company_type": "GmbH",
    "registered_location": "2",
    "unified_social_credit": "UVWXYZ12345678901",
    "registered_address": "Berlin",
    "registered_phone": "49123456789",
    "company_email": "info@xyzgmbh.com",
    "establishment_date": "2022-05-20",
    "registered_capital": 800000.00,
    "legal_representative_name": "Max Mustermann",
    "legal_representative_phone": "49987654321",
    "legal_representative_id": "D987654",
    "industry": "制造业",
    "business_scope": "汽车零部件生产",
    "verified_customer": True,
    "szse_member": False,
    "szse_member_code": "",
    "szse_member_abbreviation": "",
    "customer_status": "正常",
    "country": "德国",
    "province": "柏林",
    "city": "柏林市",
    "business_license_number": "876543210",
    "business_license_expiry": "2026-05-31",
    "primary_contact_name": "Anna Schmidt",
    "primary_contact_position": "经理",
    "primary_contact_phone": "+49-678912345",
    "primary_contact_email": "anna.schmidt@xyzgmbh.com"
},
{
  "company_code": "C005",
  "company_name": "EFG有限公司",
  "company_abbreviation": "EFG",
  "company_type": "有限公司",
  "registered_location": "0",
  "unified_social_credit": "9876543210ABCDE01",
  "registered_address": "上海市浦东新区",
  "registered_phone": "021-98765432",
  "company_email": "info@efg.com",
  "establishment_date": "2022-07-01",
  "registered_capital": 800000.00,
  "legal_representative_name": "王五",
  "legal_representative_phone": "13987654321",
  "legal_representative_id": "D987654",
  "industry": "金融业",
  "business_scope": "投资管理",
  "verified_customer": True,
  "szse_member": True,
  "szse_member_code": "SZ002",
  "szse_member_abbreviation": "SZ",
  "customer_status": "正常",
  "country": "中国",
  "province": "上海市",
  "city": "上海市",
  "business_license_number": "987654321",
  "business_license_expiry": "2025-07-31",
  "primary_contact_name": "赵六",
  "primary_contact_position": "经理",
  "primary_contact_phone": "13912345678",
  "primary_contact_email": "zhao.liu@efg.com"
},
{
  "company_code": "C006",
  "company_name": "KLM株式会社",
  "company_abbreviation": "KLM",
  "company_type": "株式会社",
  "registered_location": "2",
  "unified_social_credit": "1A2B3C4D5E6F7G8H9",
  "registered_address": "东京都中央区",
  "registered_phone": "81123456789",
  "company_email": "info@klm.co.jp",
  "establishment_date": "2022-11-01",
  "registered_capital": 9000000.00,
  "legal_representative_name": "山田一郎",
  "legal_representative_phone": "81987654321",
  "legal_representative_id": "F012345",
  "industry": "制造业",
  "business_scope": "汽车制造",
  "verified_customer": False,
  "szse_member": False,
  "szse_member_code": "",
  "szse_member_abbreviation": "",
  "customer_status": "Active",
  "country": "日本",
  "province": "东京都",
  "city": "东京",
  "business_license_number": "0987654321",
  "business_license_expiry": "2025-11-30",
  "primary_contact_name": "佐藤花子",
  "primary_contact_position": "经理",
  "primary_contact_phone": "+81-234-567890",
  "primary_contact_email": "sato.hanako@klm.co.jp"
},
{
  "company_code": "C007",
  "company_name": "GHI有限公司",
  "company_abbreviation": "GHI",
  "company_type": "有限公司",
  "registered_location": "2",
  "unified_social_credit": "XYZ123ABC456DEF78",
  "registered_address": "境外地址",
  "registered_phone": "+123-456789",
  "company_email": "info@ghi.com",
  "establishment_date": "2022-03-01",
  "registered_capital": 3000000.00,
  "legal_representative_name": "赵四",
  "legal_representative_phone": "+123-456789",
  "legal_representative_id": "C987654",
  "industry": "服务业",
  "business_scope": "咨询服务",
  "verified_customer": False,
  "szse_member": False,
  "szse_member_code": "",
  "szse_member_abbreviation": "",
  "customer_status": "正常",
  "country": "境外",
  "province": "境外省份",
  "city": "境外城市",
  "business_license_number": "654321098",
  "business_license_expiry": "2025-03-01",
  "primary_contact_name": "钱七",
  "primary_contact_position": "经理",
  "primary_contact_phone": "+123-456789",
  "primary_contact_email": "qian.qi@ghi.com"
},
{
  "company_code": "C008",
  "company_name": "JKL有限公司",
  "company_abbreviation": "JKL",
  "company_type": "有限公司",
  "registered_location": "0",
  "unified_social_credit": "65432109876543210",
  "registered_address": "北京市海淀区",
  "registered_phone": "010-98765432",
  "company_email": "info@jkl.com",
  "establishment_date": "2022-04-01",
  "registered_capital": 4000000.00,
  "legal_representative_name": "王八",
  "legal_representative_phone": "010-98765432",
  "legal_representative_id": "D987654",
  "industry": "科技",
  "business_scope": "软件开发",
  "verified_customer": True,
  "szse_member": True,
  "szse_member_code": "SZ002",
  "szse_member_abbreviation": "SZ",
  "customer_status": "正常",
  "country": "中国",
  "province": "北京市",
  "city": "北京",
  "business_license_number": "789654321",
  "business_license_expiry": "2025-04-01",
  "primary_contact_name": "孙九",
  "primary_contact_position": "经理",
  "primary_contact_phone": "010-12345678",
  "primary_contact_email": "sun.jiu@jkl.com"
},
{
  "company_code": "C009",
  "company_name": "MNO公司",
  "company_abbreviation": "MNO",
  "company_type": "有限公司",
  "registered_location": "1",
  "unified_social_credit": "00000000000000000",
  "registered_address": "香港岛湾仔区",
  "registered_phone": "852-12345678",
  "company_email": "info@mno.com",
  "establishment_date": "2022-05-01",
  "registered_capital": 5000000.00,
  "legal_representative_name": "赵十",
  "legal_representative_phone": "852-12345678",
  "legal_representative_id": "E987654",
  "industry": "零售",
  "business_scope": "电子产品",
  "verified_customer": True,
  "szse_member": False,
  "szse_member_code": "",
  "szse_member_abbreviation": "",
  "customer_status": "正常",
  "country": "中国",
  "province": "香港",
  "city": "香港",
  "business_license_number": "9876543210",
  "business_license_expiry": "2025-05-01",
  "primary_contact_name": "周十一",
  "primary_contact_position": "经理",
  "primary_contact_phone": "852-98765432",
  "primary_contact_email": "zhou.shiyi@mno.com"
},
{
  "company_code": "C010",
  "company_name": "XYZ Enterprises",
  "company_abbreviation": "XYZ",
  "company_type": "Retail",
  "registered_location": "2",
  "unified_social_credit": "11111111111111111",
  "registered_address": "123 Main Street",
  "registered_phone": "987-654-3210",
  "company_email": "info@abccorp.com",
  "establishment_date": "2010-01-15",
  "registered_capital": 1000000.00,
  "legal_representative_name": "John Johnson",
  "legal_representative_phone": "555-123-4567",
  "legal_representative_id": "123456789",
  "industry": "Consumer Goods",
  "business_scope": "Wholesale distribution",
  "verified_customer": True,
  "szse_member": False,
  "szse_member_code": "",
  "szse_member_abbreviation": "",
  "customer_status": "Active",
  "country": "China",
  "province": "Beijing",
  "city": "Beijing",
  "business_license_number": "BL123456",
  "business_license_expiry": "2023-09-30",
  "primary_contact_name": "Emily Smith",
  "primary_contact_position": "Sales Manager",
  "primary_contact_phone": "555-987-6543",
  "primary_contact_email": "emily@abccorp.com"
},
{
  "company_code": "C011",
  "company_name": "LMN有限公司",
  "company_abbreviation": "LMN",
  "company_type": "制造业",
  "registered_location": "0",
  "unified_social_credit": "22222222222222222",
  "registered_address": "上海市浦东新区",
  "registered_phone": "021-98765432",
  "company_email": "info@lmn.com",
  "establishment_date": "2015-10-01",
  "registered_capital": 3000000.00,
  "legal_representative_name": "张三",
  "legal_representative_phone": "021-98765432",
  "legal_representative_id": "A987654",
  "industry": "制造业",
  "business_scope": "电子产品制造",
  "verified_customer": True,
  "szse_member": False,
  "szse_member_code": "",
  "szse_member_abbreviation": "",
  "customer_status": "正常",
  "country": "中国",
  "province": "上海市",
  "city": "上海",
  "business_license_number": "987654321",
  "business_license_expiry": "2024-10-01",
  "primary_contact_name": "李四",
  "primary_contact_position": "经理",
  "primary_contact_phone": "021-12345678",
  "primary_contact_email": "li.si@lmn.com"
},
{
  "company_code": "C012",
  "company_name": "OPQ有限公司",
  "company_abbreviation": "OPQ",
  "company_type": "服务业",
  "registered_location": "0",
  "unified_social_credit": "33333333333333333",
  "registered_address": "广州市天河区",
  "registered_phone": "020-12345678",
  "company_email": "info@abc.com",
  "establishment_date": "2010-05-15",
  "registered_capital": 5000000.00,
  "legal_representative_name": "李五",
  "legal_representative_phone": "020-12345678",
  "legal_representative_id": "B123456",
  "industry": "广告",
  "business_scope": "广告策划与设计",
  "verified_customer": True,
  "szse_member": True,
  "szse_member_code": "SZ001",
  "szse_member_abbreviation": "SZ001",
  "customer_status": "正常",
  "country": "中国",
  "province": "广东省",
  "city": "广州",
  "business_license_number": "123456789",
  "business_license_expiry": "2023-12-31",
  "primary_contact_name": "王六",
  "primary_contact_position": "经理",
  "primary_contact_phone": "020-98765432",
  "primary_contact_email": "wang.liu@abc.com"
},
{
  "company_code": "C013",
  "company_name": "XYZ有限公司",
  "company_abbreviation": "XYZ",
  "company_type": "贸易",
  "registered_location": "0",
  "unified_social_credit": "44444444444444444",
  "registered_address": "深圳市福田区",
  "registered_phone": "0755-12345678",
  "company_email": "info@xyz.com",
  "establishment_date": "2018-09-20",
  "registered_capital": 2000000.00,
  "legal_representative_name": "赵八",
  "legal_representative_phone": "0755-12345678",
  "legal_representative_id": "C123456",
  "industry": "贸易",
  "business_scope": "进出口业务",
  "verified_customer": True,
  "szse_member": False,
  "szse_member_code": "",
  "szse_member_abbreviation": "",
  "customer_status": "正常",
  "country": "中国",
  "province": "广东省",
  "city": "深圳",
  "business_license_number": "9876543210",
  "business_license_expiry": "2024-09-20",
  "primary_contact_name": "钱九",
  "primary_contact_position": "经理",
  "primary_contact_phone": "0755-98765432",
  "primary_contact_email": "qian.jiu@xyz.com"
},
{
    "company_code": "C014",
    "company_name": "AAA有限公司",
    "company_abbreviation": "AAA",
    "registered_location": "0",
    "company_type": "金融",
    "unified_social_credit": "55555555555555555",
    "registered_address": "北京市朝阳区",
    "registered_phone": "010-12345678",
    "company_email": "info@efg.com",
    "establishment_date": "2019-07-10",
    "registered_capital": 8000000.00,
    "legal_representative_name": "孙十",
    "legal_representative_phone": "010-12345678",
    "legal_representative_id": "D123456",
    "industry": "金融",
    "business_scope": "投资管理",
    "verified_customer": True,
    "szse_member": True,
    "szse_member_code": "SZ003",
    "szse_member_abbreviation": "SZ003",
    "customer_status": "正常",
    "country": "中国",
    "province": "北京市",
    "city": "北京",
    "business_license_number": "3456789012",
    "business_license_expiry": "2023-07-10",
    "primary_contact_name": "周十一",
    "primary_contact_position": "经理",
    "primary_contact_phone": "010-98765432",
    "primary_contact_email": "zhou.shiyi@efg.com"
}

]



# 发送POST请求
i = 0
for form in forms:
    send_post_request(url, headers=headers, data=form)